import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';
import { registerSW } from 'virtual:pwa-register';

// Register service worker (generated by vite-plugin-pwa / Workbox)
const updateSW = registerSW({
  onNeedRefresh() {
    if (confirm('A new version of HumScore is available. Reload to update?')) {
      updateSW(true);
    }
  },
  onOfflineReady() {
    console.log('[HumScore] Ready to work offline.');
  },
});

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
